# User module schema: user.schema.yml

# User mails.
user.mail:
 type: mapping
 mapping:
  "cancel_confirm":
    type: mail
    label: "Account cancellation confirmation"
  "password_reset":
    type: mail
    label: "Password reset email"
  "register_admin_created":
    type: mail
    label: "Account created by administrator"
  "register_no_approval_required":
    type: mail
    label: "Registration confirmation (No approval required)"
  "register_pending_approval":
    type: mail
    label: "Registration confirmation (Pending approval)"
  "status_activated":
    type: mail
    label: "Account activation"
  "status_blocked":
    type: mail
    label: "Account blocked"
  "status_canceled":
    type: mail
    label: "Account cancelled"

# User settings.
user.settings:
  type: mapping
  mapping:
    "admin_role":
      type: string
      label: "Administrator role"
    "anonymous":
      type: label
      label: "Anonymous name"
    "verify_mail":
      type: boolean
      label: "Verify mail"
    "notify":
      type: mapping
      label: "Notify user"
      mapping:
        "cancel_confirm":
          type: boolean
        "password_reset":
          type: boolean
        "status_activated":
          type: boolean
        "status_blocked":
          type: boolean
        "status_cancelled":
          type: boolean
        "register_admin_created":
          type: boolean
        "register_no_approval_required":
          type: boolean
        "register_pending_approval":
          type: boolean
    "register":
      type: string
      enum: [visitors, admin_only, visitors_admin_approval]
    "signatures":
      type: boolean
      label: "User signatures"
    "cancel_method":
      type: string
      label: "User cancel method"
    "password_reset_timeout":
      type: integer
