<?php

/**
 * @file
 * Install, update and uninstall functions for the entity_test module.
 */

/**
 * Implements hook_install().
 */
function entity_test_install() {
  $entity_types = array(
    'entity_test',
    'entity_test_rev',
    'entity_test_mul',
    'entity_test_mulrev',
  );
  foreach ($entity_types as $entity_type) {
    // Auto-create fields for testing.
    entity_create('field_config', array(
      'name' => 'field_test_text',
      'entity_type' => $entity_type,
      'type' => 'text',
      'cardinality' => 1,
      'translatable' => FALSE,
    ))->save();
    entity_create('field_instance_config', array(
      'entity_type' => $entity_type,
      'field_name' => 'field_test_text',
      'bundle' => $entity_type,
      'label' => 'Test text-field',
    ))->save();

    entity_get_form_display($entity_type, $entity_type, 'default')
      ->setComponent('field_test_text', array('type' => 'text_textfield'))
      ->save();
  }
}
