base_field: nid
base_table: node
core: 8.x
description: 'A list of nodes marked for display on the front page.'
status: '1'
display:
  default:
    display_options:
      access:
        type: perm
      cache:
        type: none
      empty:
        area_text_custom:
          admin_label: ''
          content: 'No front page content has been created yet.'
          empty: '1'
          field: area_text_custom
          group_type: group
          id: area_text_custom
          label: ''
          relationship: none
          table: views
          tokenize: '0'
          plugin_id: text
        node_listing_empty:
          admin_label: ''
          empty: '1'
          field: node_listing_empty
          group_type: group
          id: node_listing_empty
          label: ''
          relationship: none
          table: node
          plugin_id: node_listing_empty
        title:
          id: title
          table: views
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          empty: '1'
          title: 'Welcome to [site:name]'
          plugin_id: title
      exposed_form:
        type: basic
      filters:
        promote:
          admin_label: ''
          expose:
            description: ''
            identifier: ''
            label: ''
            multiple: '0'
            operator: ''
            operator_id: '0'
            remember: '0'
            remember_roles:
              authenticated: authenticated
            required: '0'
            use_operator: '0'
          exposed: '0'
          field: promote
          group: '1'
          group_info:
            default_group: All
            default_group_multiple: {  }
            description: ''
            group_items: {  }
            identifier: ''
            label: ''
            multiple: '0'
            optional: '1'
            remember: '0'
            widget: select
          group_type: group
          id: promote
          is_grouped: '0'
          operator: '='
          relationship: none
          table: node
          value: '1'
          plugin_id: boolean
        status:
          expose:
            operator: '0'
          field: status
          group: '1'
          id: status
          table: node
          value: '1'
          plugin_id: boolean
      pager:
        options:
          items_per_page: '10'
        type: full
      query:
        type: views_query
      row:
        options:
          build_mode: teaser
          comments: '0'
          links: '1'
        type: node
      sorts:
        sticky:
          admin_label: ''
          expose:
            label: ''
          exposed: '0'
          field: sticky
          group_type: group
          id: sticky
          order: DESC
          relationship: none
          table: node
          plugin_id: boolean
        created:
          field: created
          id: created
          order: DESC
          table: node
          plugin_id: date
      style:
        type: default
      title: ''
    display_plugin: default
    display_title: Master
    id: default
    position: 0
  page_1:
    display_options:
      path: node
    display_plugin: page
    display_title: Page
    id: page_1
    position: 1
  feed_1:
    display_plugin: feed
    id: feed_1
    display_title: Feed
    position: 2
    display_options:
      sitename_title: '1'
      path: rss.xml
      displays:
        page_1: page_1
        default: '0'
label: Frontpage
module: node
id: frontpage
tag: 'default'
langcode: en
