<?php

/**
 * @file
 * Helper module for the path tests.
 */

/**
 * Resets the path test results.
 */
function path_test_reset() {
  \Drupal::state()->set('path_test.results', array());
}

/**
 * Implements hook_path_insert().
 */
function path_test_path_insert($path, array $options = array()) {
  if (empty($options['skip_log'])) {
    $results = Drupal::state()->get('path_test.results') ?: array();
    $results['hook_path_insert'][] = $path;
    Drupal::state()->set('path_test.results', $results);
  }
}

/**
 * Implements hook_path_update().
 */
function path_test_path_update($path, array $options = array()) {
  $results = \Drupal::state()->get('path_test.results') ?: array();
  $results['hook_path_update'] = $path;
  \Drupal::state()->set('path_test.results', $results);
}
