id: taxonomy.term.forums
targetEntityType: taxonomy.term
bundle: forums
types:
  - 'sioc:Container'
  - 'sioc:Forum'
fieldMappings:
  name:
    properties:
      - 'schema:name'
  description:
    properties:
      - 'schema:description'
