<?php

/**
 * @file
 * Install, update, and uninstall functions for the Field SQL Storage module.
 */

use Drupal\field\Plugin\Core\Entity\Field;

/**
 * Implements hook_update_dependencies().
 */
function field_sql_storage_update_dependencies() {
  // Convert storage tables after field definitions have moved to
  // ConfigEntities.
  $dependencies['field_sql_storage'][8000] = array(
    'field' => 8003,
  );
  return $dependencies;
}
