admin_role: ''
anonymous: Anonymous
verify_mail: '1'
notify:
  cancel_confirm: '1'
  password_reset: '1'
  status_activated: '1'
  status_blocked: '0'
  status_cancelled: '0'
  register_admin_created: '1'
  register_no_approval_required: '1'
  register_pending_approval: '1'
register: visitors
signatures: '0'
