id: d6_contact_settings
source:
    plugin: drupal6_variable
    variables:
        - contact_default_status
        - contact_threshold_limit
        - contact_threshold_window
process:
    user_default_enabled: contact_default_status
    'flood:limit': contact_threshold_limit
    'flood:interval': contact_threshold_window
destination:
    plugin: d8_config
    config_name: contact.settings
