id: node.article.field_tags
field_name: field_tags
bundle: article
label: Tags
description: 'Enter a comma-separated list of words to describe your content.'
required: false
default_value: {  }
default_value_function: ''
settings:
  user_register_form: false
status: 1
langcode: und
