id: taxonomy_term_description
type: text_long
module: text
active: '1'
settings: {  }
storage:
  type: field_sql_storage
  settings: {  }
  module: field_sql_storage
  active: '1'
locked: '0'
cardinality: '1'
translatable: '0'
entity_types: {  }
indexes: {  }
status: 1
langcode: und
