format: restricted_html
name: 'Restricted HTML'
status: '1'
weight: '0'
roles:
  - anonymous
cache: '1'
filters:
  filter_url:
    module: filter
    status: '1'
  filter_html:
    module: filter
    status: '1'
    setttings:
      filter_html_nofollow: '1'
  filter_autop:
    module: filter
    status: '1'
  filter_htmlcorrector:
    module: filter
    status: '1'
langcode: en
