id: search_form_block
status: '1'
cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
subject: 'Search'
module: search
region: sidebar_first
weight: '0'
