id: 'system_menu_block:menu-footer'
status: '1'
cache: '-1'
subject: 'Footer menu'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
module: system
region: footer
weight: '0'
