id: user_login_block
whois_new_count: '5'
status: '1'
cache: '-1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
  visibility__active_tab: edit-visibility-path
subject: 'User login'
module: user
region: content
weight: '10'
