id: user.user
targetEntityType: user
bundle: user
types:
  - 'sioc:UserAccount'
fieldMappings:
  name:
    properties:
      - 'foaf:name'
  homepage:
    properties:
      - 'foaf:page'
    mapping_type: 'rel'
