id: stark.admin
label: Administration
region: sidebar_first
weight: '1'
module: system
status: '1'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types: {  }
  visibility__active_tab: edit-visibility-path
plugin: 'system_menu_block:menu-admin'
settings:
  cache: '-1'
