# Schema for the configuration files of the text module.

text.settings:
  type: mapping
  label: 'Text settings'
  mapping:
    default_summary_length:
      type: integer
      label: 'Default summary length'
