# Schema for configuration files of the menu module.

menu.settings:
  type: mapping
  label: 'Menu settings'
  mapping:
    main_links:
      type: string
      label: 'Main links'
    secondary_links:
      type: string
      label: 'Source for secondary links'
    override_parent_selector:
      type: boolean
      label: 'Override parent selector'

menu.menu.*:
  type: mapping
  label: 'Menu'
  mapping:
    id:
      type: string
      label: 'Menu identifier'
    label:
      type: string
      label: 'Menu label'
    description:
      type: text
      label: 'Menu description'
