id: d6_menu
sourceIds:
  menu_name:
    type: string
source:
  plugin: drupal6_menu
process:
  id: menu_name
  label: title
  description: description
destination:
  plugin: entity
  entity_type: menu
