id: d6_contact_category

source:
  plugin: drupal6_contact_category

process:
  id:
    -
      plugin: machine_name
      source: category
    -
      plugin: dedupe_entity
      entity_type: user_role
      field: cid
  label: category
  recipients: recipients
  reply: reply
  weight: weight

destination:
  plugin: entity
  entity_type: contact_category
