id: d6_taxonomy_vocabulary
sourceIds:
  vid:
    type: string
destinationIds:
  vid:
    type: string
source:
  plugin: drupal6_taxonomy_vocabulary
process:
  vid:
    -
      plugin: machine_name
      source: name
    -
      plugin: dedupe_entity
      entity_type: taxonomy_vocabulary
      field: vid
  label: name
  name: name
  description: description
  hierarchy: hierarchy
  weight: weight
destination:
  plugin: entity
  entity_type: taxonomy_vocabulary
