id: d6_date_formats
sourceIds:
  name:
    type: string
destinationIds:
  id:
    type: string
source:
  plugin: drupal6_variable_multirow
  variables:
    - date_format_long
    - date_format_medium
    - date_format_short
process:
  id:
    plugin: static_map
    source: name
    map:
      date_format_long: long
      date_format_short: short
      date_format_medium: medium
  'pattern:php': value
destination:
  plugin: entity_date_format
