id: d6_comment
sourceIds:
  cid:
    type: integer
source:
  plugin: drupal6_comment
  constants:
    field_id: node__comment
    entity_type: node
process:
  cid: cid
  pid:
    -
      plugin: drupal6_comment_pid
    -
      plugin: migration
      migration: d6_comment
      source:
        - pid
    -
      plugin: extract
      index:
        - 0
  entity_id: nid
#    -
#      plugin: migration
#      migration: drupal6_node
#      source:
#        - nid
#    -
#      plugin: extract
#      index:
#        - 0
  entity_type: constants:node
  field_id: constants:field_id
  subject: subject
  uid: uid
#    -
#      plugin: migration
#      migration: drupal6_user
#      source:
#        - uid
#    -
#      plugin: extract
#      index:
#        - 0
  name: name
  mail: mail
  homepage: homepage
  hostname: hostname
  created: timestamp
  changed: timestamp
  status: status #ToDo: In D6, published=0.
  thread: thread
  'comment_body:value': comment
  'comment_body:format':
    -
      plugin: migration
      migration: d6_filter_format
      source:
        - format
    -
      plugin: extract
      index:
        - 0
destination:
  plugin: entity_comment
