id: d6_system_filter
source:
  plugin: variable
  variables:
    - filter_allowed_protocols:
      - http
      - https
      - ftp
      - news
      - nntp
      - tel
      - telnet
      - mailto
      - irc
      - ssh
      - sftp
      - webcal
      - rtsp
process:
  protocols: filter_allowed_protocols
destination:
  plugin: config
  config_name: system.filter
