id: d6_file
source:
  plugin: d6_file
process:
  fid: fid
  filename: filename
  uri:
    plugin: file_uri
    source:
      - filepath
      - file_directory_path
      - is_public
  filemime: filemime
  filesize: filesize
  status: status
  changed: timestamp
destination:
  plugin: entity:file
