id: d6_field_instance

source:
  plugin: drupal6_field_instance
  constants:
    entity_type: node

process:
  entity_type: constants.entity_type
  field_name: field_name
  bundle: type_name
  label: label
  description: description
  required: required
  status: active
  settings:
    plugin: drupal6_field_instance_settings
    source:
      - widget_type
      - widget_settings
      - global_settings

  default_value_function: ''
  default_value:
    plugin: drupal6_field_instance_defaults
    source:
      - widget_type
      - widget_settings

destination:
  plugin: entity:field_instance
dependencies:
  - d6_node
  - d6_field
