id: d6_upload_field
source:
  # We do an empty source and a proper destination to have an idmap for
  # dependencies.
  plugin: d6_upload_field
  constants:
    entity_type: node
    type: file
    name: upload
    cardinality: -1
    display_field: true
process:
  entity_type: constants.entity_type
  name: constants.name
  type: constants.type
  cardinality: constants.cardinality
  settings.display_field: constants.display_field
destination:
  plugin: entity:field_config
