id: d6_node_type_entity_form_display
source:
  plugin: drupal6_node_type
  constants:
    entity_type: node
    field_name: body
    form_mode: default
    options:
      type: text_textarea_with_summary
process:
  entity_type: constants.entity_type
  field_name: constants.field_name
  form_mode: constants.form_mode
  options: constants.options

  bundle: type
destination:
  plugin: entity:entity_form_display
