id: d6_term_node_revision
load:
  plugin: d6_term_node
  bundle_migration: d6_vocabulary_field

source:
  plugin: d6_term_node_revision

process:
  vid: vid
  # The actual field name is dynamic and will be added by the load plugin.

destination:
  plugin: entity_revision:node
dependencies:
  - d6_term_node
  - d6_node_revision
