configuration:
  - d6_action_settings
  - d6_aggregator_settings
  - d6_book_settings
  - d6_cck_field_values:*
  - d6_cck_field_revision:*
  - d6_comment_entity_display
  - d6_comment_entity_form_display
  - d6_comment_field
  - d6_comment_field_instance
  - d6_contact_category
  - d6_contact_settings
  - d6_date_formats
  - d6_dblog_settings
  - d6_field
  - d6_field_instance
  - d6_field_instance_widget_settings
  - d6_field_settings
  - d6_field_formatter_settings
  - d6_file_settings
  - d6_filter_format
  - d6_forum_settings
  - d6_locale_settings
  - d6_menu_settings
  - d6_menu
  - d6_node_settings
  - d6_node_type
  - d6_search_page
  - d6_search_settings
  - d6_simpletest_settings
  - d6_statistics_settings
  - d6_syslog_settings
  - d6_system_cron
  - d6_system_file
  - d6_system_filter
  - d6_system_image
  - d6_system_image_gd
  - d6_system_maintenance
  - d6_system_performance
  - d6_system_rss
  - d6_system_site
  - d6_system_theme
  - d6_taxonomy_settings
  - d6_taxonomy_vocabulary
  - d6_text_settings
  - d6_update_settings
  - d6_upload_entity_display
  - d6_upload_entity_form_display
  - d6_upload_field
  - d6_upload_field_instance
  - d6_user_mail
  - d6_user_profile_field_instance
  - d6_user_profile_entity_display
  - d6_user_profile_entity_form_display
  - d6_user_profile_field
  - d6_user_picture_entity_display
  - d6_user_picture_entity_form_display
  - d6_user_picture_field_instance
  - d6_user_picture_field
  - d6_user_role
  - d6_view_modes
  - d6_vocabulary_entity_display
  - d6_vocabulary_entity_form_display
  - d6_vocabulary_field_instance
  - d6_vocabulary_field
