id: d6_node
load:
  plugin: d6_node
source:
  plugin: drupal6_node

process:
  nid: nid
  type: type
  langcode: language
  title: title
  uid: uid
  status: status
  created: created
  changed: changed
  promote: promote
  sticky: sticky
  body.format:
    -
      plugin: migration
      migration: d6_filter_format
      source:
        - format
    -
      plugin: extract
      index:
        - 0
  body.value: body

#  unmapped d6 fields.
#  tnid
#  translate
#  moderate
#  comment

destination:
  plugin: entity:node
