id: d6_field

source:
  plugin: d6_field

process:
  entity_type:
    plugin: default_value
    default_value: node
  id:
    plugin: field_id_generator
    source:
      - @entity_type
      - field_name
  status: active
  langcode:
    plugin: default_value
    default_value: und
  name: field_name

  type:
    -
      plugin: static_map
      bypass: true
      source:
        - type
      map:
        number_integer: number_integer
        number_decimal: number_float
        number_float: number_float
        text: text
        email: email
        link: link
        date: datetime
        datestamp: datetime
        datetime: datetime
        fr_phone: telephone
        be_phone: telephone
        it_phone: telephone
        el_phone: telephone
        ch_phone: telephone
        ca_phone: telephone
        cr_phone: telephone
        pa_phone: telephone
        gb_phone: telephone
        ru_phone: telephone
        ua_phone: telephone
        es_phone: telephone
        au_phone: telephone
        cs_phone: telephone
        hu_phone: telephone
        pl_phone: telephone
        nl_phone: telephone
        se_phone: telephone
        za_phone: telephone
        il_phone: telephone
        nz_phone: telephone
        br_phone: telephone
        cl_phone: telephone
        cn_phone: telephone
        hk_phone: telephone
        mo_phone: telephone
        ph_phone: telephone
        sg_phone: telephone
        jo_phone: telephone
        eg_phone: telephone
        pk_phone: telephone
        int_phone: telephone
    -
      plugin: file_image_handler

  settings:
    plugin: field_settings
    source:
      - @type
      - global_settings
      - widget_settings

destination:
  plugin: entity:field_config
dependencies:
  # It is not possible to make this a requirement as d6_field_settings has no
  # source id. However it also has no requirements so it will always run so a
  # dependency is enough.
  - d6_field_settings: false
