id: d6_date_formats
sourceIds:
  name:
    type: varchar
    "not null": true
    length: 128
destinationIds:
  id:
    type: varchar
    length: 255
source:
  plugin: drupal6_variable_multirow
  variables:
    - date_format_long
    - date_format_medium
    - date_format_short
process:
  id:
    plugin: static_map
    source: name
    map:
      date_format_long: long
      date_format_short: short
      date_format_medium: medium
  'pattern:php': value
destination:
  plugin: entity
  entity_type: date_format
