id: d6_user
source:
  plugin: d6_user
load:
  plugin: drupal_entity
process:
  uid: uid
  name: name
  pass: pass
  mail: mail
  created: created
  access: access
  login: login
  status: status
  timezone:
    plugin: user_update_7002
    source: timezone
  preferred_langcode: language
  init: init
  roles:
    plugin: migration
    migration: d6_user_role
    source: roles
  signature: signature
  signature_format:
    plugin: migration
    migration: d6_filter_format
    source: signature_format
  user_picture:
    plugin: migration
    migration: d6_user_picture_file
    source: uid
destination:
  plugin: entity:user
  md5_passwords: true
dependencies:
  - d6_filter_format
  - d6_user_role
  - d6_user_profile_field
  - d6_user_profile_field_instance
  - d6_user_picture_file
