id: d6_menu_settings
source:
    plugin: drupal6_variable
    variables:
        - menu_primary_links_source
        - menu_secondary_links_source
        - menu_override_parent_selector
process:
    main_links: menu_primary_links_source
    secondary_links: menu_secondary_links_source
    override_parent_selector: menu_override_parent_selector
destination:
    plugin: config
    config_name: menu.settings
dependencies:
  - d6_menu
