id: d6_system_site
source:
    plugin: drupal6_variable
    variables:
        - site_name
        - site_mail
        - site_slogan
        - site_403
        - site_404
        - site_frontpage
        - admin_compact_mode
process:
    name: site_name
    mail: site_mail
    slogan: site_slogan
    'page:403': site_403
    'page:404': site_404
    'page:front': site_frontpage
    admin_compact_mode: admin_compact_mode
destination:
    plugin: d8_config
    config_name: system.site
