id: d6_vocabulary_entity_form_display
source:
  plugin: drupal6_taxonomy_vocabulary_per_type
  constants:
    entity_type: node
    form_mode: default
    options:
      type: taxonomy_term_reference
      weight: 20
process:
  entity_type: constants.entity_type
  form_mode: constants.form_mode
  options: constants.options
  bundle: type
  field_name:
    plugin: migration
    migration: d6_taxonomy_vocabulary
    source: vid
destination:
  plugin: component_entity_form_display
dependencies:
  - d6_taxonomy_vocabulary
  - d6_vocabulary_field_instance

