id: d6_comment
source:
  plugin: d6_comment
  constants:
    field_id: node__comment
    entity_type: node
process:
  cid: cid
  pid:
    -
      plugin: d6_comment_pid
      source: pid
    -
      plugin: migration
      migration: d6_comment
  entity_id:
    plugin: migration
    migration: d6_node
    source: nid
  entity_type: constants.node
  field_id: constants.field_id
  subject: subject
  uid:
    plugin: migration
    migration: d6_user
    source: uid
  name: name
  mail: mail
  homepage: homepage
  hostname: hostname
  created: timestamp
  changed: timestamp
  status: status #In D6, published=0. We reverse the value in prepareRow.
  thread: thread
  'comment_body.value': comment
  'comment_body.format':
    plugin: migration
    migration: d6_filter_format
    source: format
destination:
  plugin: entity:comment
dependencies:
  - d6_node
  - d6_user
  - d6_filter_format
