id: d6_node_type_entity_display
source:
  plugin: d6_node_type
  constants:
    entity_type: node
    field_name: body
    view_mode: default
    options:
      label: hidden
      type: text_default
process:
  entity_type: constants.entity_type
  field_name: constants.field_name
  view_mode: constants.view_mode
  options: constants.options

  bundle: type
destination:
  plugin: component_entity_display
dependencies:
  - d6_node_body_instance
