id: d6_vocabulary_field_instance
source:
  plugin: drupal6_taxonomy_vocabulary_per_type
  constants:
    entity_type: node
    parent: 0

process:
  entity_type: constants.entity_type
  bundle: type
  field_name:
    plugin: migration
    migration: d6_taxonomy_vocabulary
    source: vid
  'settings.allowed_values.0.vocabulary': @field_name
  'settings.allowed_values.0.parent': constants.parent
destination:
  plugin: entity:field_instance
dependencies:
  - d6_taxonomy_vocabulary
  - d6_vocabulary_field
