id: d6_taxonomy_term
source:
  plugin: d6_taxonomy_term
process:
  tid: tid
  vid:
    plugin: migration
    migration: d6_taxonomy_vocabulary
    source: vid
  name: name
  description: description
  weight: weight
  parent:
    plugin: migration
    migration: d6_taxonomy_term
    source: parent
  changed: timestamp
destination:
  plugin: entity:taxonomy_term
dependencies:
  - d6_taxonomy_vocabulary
