id: d6_node_type
source:
  plugin: drupal6_node_type
  constants:
    preview: 1 # DRUPAL_OPTIONAL
process:
  type:
    -
      plugin: machine_name
      source: type
  name: name
  module: module
  description: description
  help: help
  has_title: has_title
  title_label: title_label
  preview: constants:preview
  submitted: submitted
  options: options

destination:
  plugin: entity
  entity_type: node_type
