id: d6_term_node
load:
  plugin: d6_term_node
  bundle_migration: d6_vocabulary_field

source:
  plugin: d6_term_node

process:
  nid: nid
  # The actual field name is dynamic and will be added by the load plugin.

destination:
  plugin: entity:node
dependencies:
  - d6_vocabulary_field_instance
  - d6_vocabulary_entity_display
  - d6_vocabulary_entity_form_display
  - d6_node
