id: d6_view_modes

sourceIds:
  view_mode:
    type: string

destinationIds:
  id:
    type: string

source:
  plugin: drupal6_view_mode

process:
  mode:
    plugin: static_map
    source: view_mode
    map:
      0: normal
      1: preview
      2: search_index
      3: search_result
      4: rss
      5: print
      teaser: teaser
      full: full
  label:
    plugin: static_map
    source: view_mode
    map:
      0: "Normal"
      1: "Preview"
      2: "Search index"
      3: "Search result"
      4: "RSS"
      5: "Print"
      teaser: "Teaser"
      full: "Full"
  targetEntityType:
    plugin: default_value
    default_value: node
  id:
    plugin: concat
    delimiter: .
    source:
      - @targetEntityType
      - @mode
  status:
    plugin: default_value
    default_value: true

destination:
  plugin: entity
  entity_type: view_mode
