id: d6_node_revision
load:
  plugin: drupal_entity
  bundle_migration: d6_node_type

source:
  plugin: drupal6_node_revision

process:
  nid: nid
  type: type
  langcode: language
  title: title
  uid: uid
  status: status
  created: created
  changed: changed
  promote: promote
  sticky: sticky
  body.format:
    plugin: migration
    migration: d6_filter_format
    source: format
  body.value: body

#  unmapped d6 fields.
#  tnid
#  translate
#  moderate
#  comment

destination:
  plugin: entity_revision:node
dependencies:
  - d6_node_type
  - d6_node
