content:
  - d6_aggregator_feed
  - d6_aggregator_item
  - d6_block
  - d6_comment
  - d6_custom_block
  - d6_file
  - d6_profile_values:user
  - d6_taxonomy_term
  - d6_term_node_revision:*
  - d6_term_node:*
  - d6_upload
  - d6_url_alias
  - d6_user
  - d6_user_picture_file
