id: d6_upload

source:
  plugin: d6_upload

process:
  nid: nid
  vid: vid
  upload:
    plugin: iterator
    source: upload
    process:
      target_id:
        plugin: migration
        migration: d6_file
        source: fid
      display: list
      description: description
destination:
  plugin: entity:node
dependencies:
  - d6_file
  - d6_node
