id: d6_comment_entity_form_display
source:
  plugin: d6_comment_variable
  constants:
    entity_type: node
    field_name: comment
    form_mode: default
    options:
      type: comment_default
      weight: 20
process:
  entity_type: constants.entity_type
  field_name: constants.field_name
  form_mode: constants.form_mode
  options: constants.options

  bundle: node_type
destination:
  plugin: component_entity_form_display
