id: d6_node_body_field
source:
  # We do an empty source and a proper destination to have an idmap for
  # dependencies.
  plugin: empty
  constants:
    entity_type: node
    type: text_with_summary
    name: body
    cardinality: 1
process:
  entity_type: constants.entity_type
  name: constants.name
  type: constants.type
  cardinality: constants.cardinality
destination:
  plugin: entity:field_config
