id: d6_vocabulary_to_field
sourceIds:
  vid:
    type: integer
destinationIds:
  id:
    type: string
source:
  plugin: drupal6_taxonomy_vocabulary

process:
  entity_type:
    plugin: default_value
    default_value: node
  name:
    -
      plugin: migration
      migration: d6_taxonomy_vocabulary
      source:
        - vid
    -
      plugin: extract
      index:
        - 0
  type:
    plugin: default_value
    default_value: taxonomy_term_reference
  'settings:allowed_values:0:vocabulary': @name
destination:
  plugin: entity_field_entity
