id: d6_upload_entity_display
source:
  plugin: drupal6_upload_instance
  constants:
    entity_type: node
    view_mode: default
    name: upload
    type: file_default
    options:
      label: hidden
      settings: {}
process:
  entity_type: constants.entity_type
  bundle: node_type
  view_mode: constants.view_mode
  field_name: constants.name
  type: constants.type
  options: constants.options
  'options.type': @type
destination:
  plugin: component_entity_display
dependencies:
  - d6_upload_field_instance
