id: d6_field_instance

sourceIds:
  field_name:
    type: string
    alias: cnfi
  type_name:
    type: string

destinationIds:
  id:
    type: string

source:
  plugin: drupal6_field_instance

process:
  entity_type:
    plugin: default_value
    default_value: node
  id:
    plugin: concat
    delimiter: .
    source:
      - @entity_type
      - type_name
      - field_name

  field_name: field_name
  bundle: type_name
  label: label
  description: description
  required: required
  status: active
  settings:
    plugin: drupal6_field_instance_settings
    source:
      - widget_type
      - widget_settings
      - global_settings

  default_value_function: ''
  default_value:
    plugin: drupal6_field_instance_defaults
    source:
      - widget_type
      - widget_settings

destination:
  plugin: entity
  entity_type: field_instance
