id: d6_user_profile_field_instance
source:
  plugin: drupal6_profile_field
  constants:
    entity_type: user
    bundle: user
process:
  entity_type: constants.entity_type
  bundle: constants.bundle
  label: title
  description: explanation
  field_name: name
  required: required
destination:
  plugin: entity:field_instance
dependencies:
  - d6_user_profile_field
