<?php

/**
 * @file
 * Contains install and update hooks.
 */

/**
 * Implements hook_install().
 */
function contact_storage_test_install() {
  $entity_manager = \Drupal::entityManager();
  $original = clone $entity_manager->getDefinition('contact_message');
  $original->setStorageClass('Drupal\Core\Entity\ContentEntityNullStorage');
  $entity_manager->getStorage($original->id())->onEntityDefinitionUpdate($original);
}
