base_field: fid
base_table: file_managed
core: 8.x
description: 'Displays file usage information for a given file.'
status: '1'
display:
  page_1:
    display_plugin: page
    id: page_1
    display_title: Page
    position: '1'
    display_options:
      path: admin/content/files/usage/%
      menu:
        type: none
        title: 'File usage'
        description: 'Usages list for a given file.'
        name: admin
        weight: '0'
        context: '0'
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: perm
        options:
          perm: 'access files overview'
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: full
        options:
          items_per_page: '10'
          offset: '0'
          id: '0'
          total_pages: ''
          expose:
            items_per_page: '0'
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 20, 40, 60'
            items_per_page_options_all: '0'
            items_per_page_options_all_label: '- All -'
            offset: '0'
            offset_label: Offset
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
          quantity: '9'
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          override: '1'
          sticky: '0'
          summary: ''
          columns:
            entity_label: entity_label
            type: type
            module: module
            count: count
          info:
            entity_label:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
            type:
              sortable: '1'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: 'priority-medium'
            module:
              sortable: '0'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: 'priority-low'
            count:
              sortable: '0'
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: '0'
              responsive: ''
          default: 'entity_label'
          empty_table: '1'
      row:
        type: fields
      fields:
        entity_label:
          id: entity_label
          table: file_usage
          field: entity_label
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Entity'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          link_to_entity: '1'
          plugin_id: file_usage_entity_label
        type:
          id: type
          table: file_usage
          field: type
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Entity type'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: standard
        module:
          id: module
          table: file_usage
          field: module
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Registering module'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: standard
        count:
          id: count
          table: file_usage
          field: count
          relationship: none
          group_type: group
          admin_label: ''
          label: 'Use count'
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '1'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
          plugin_id: numeric
      filters: {  }
      sorts: {  }
      title: 'File usage'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      arguments:
        fid:
          id: fid
          table: file_managed
          field: fid
          relationship: none
          group_type: group
          admin_label: ''
          default_action: 'not found'
          exception:
            value: all
            title_enable: '0'
            title: All
          title_enable: '1'
          title: 'File usage information for %1'
          breadcrumb_enable: '0'
          breadcrumb: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          default_argument_skip_url: '0'
          summary_options:
            base_path: ''
            count: '1'
            items_per_page: '25'
            override: '0'
          summary:
            sort_order: asc
            number_of_records: '0'
            format: default_summary
          specify_validation: '0'
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: '0'
          not: '0'
          plugin_id: file_fid
label: 'File usage'
module: file
id: file_usage
tag: 'default'
uuid: 360a2cdb-a14c-4b41-9827-3930a483caf8
langcode: en
