source:
    plugin: drupal6_filter_formats
process:
    format: format
    roles: roles
    cache: cache
    filter:
        plugin: iterator
        source: filter
        process:
            name:
                plugin: map
                source:
                    - module
                    - delta
                map:
                    filter:
                        - filter_html
                        - filter_autop
                        - filter_url
                        - filter_htmlcorrector
                        - filter_html_escape
                    php:
                        - php_code
            settings: settings
