id: d6_filter_formats
sourceIds:
    name:
        type: varchar
        length: 255
destinationIds:
    name:
        type: varchar
        length: 255
source:
    plugin: drupal6_filter_formats
process:
    # this will need the dedupe process plugin.
    format: name
    name: name
    # this will need an iterator + plugin: migration, id: role.
    roles: roles
    cache: cache
    filters:
        plugin: iterator
        source: filters
        process:
            name:
                plugin: map
                source:
                    - module
                    - delta
                map:
                    filter:
                        - filter_html
                        - filter_autop
                        - filter_url
                        - filter_htmlcorrector
                        - filter_html_escape
                    php:
                        - php_code
            settings: settings
destination:
    plugin: entity
    entity_type: filter_format
