id: d6_system_site
source:
    plugin: drupal6_variable
    variables:
        - site_name
        - site_mail
        - site_slogan
        - site_frontpage
        - site_403
        - site_404
        - drupal_weight_select_max
        - admin_compact_mode
process:
    -
        plugin: copy_from_source
        site_name: name
        site_mail: mail
        site_slogan: slogan
        site_frontpage: 'page:front'
        site_403: 'page:403'
        site_404: 'page:404'
        drupal_weight_select_max: weight_select_max
        admin_compact_mode: admin_compact_mode
destination:
    plugin: d8_config
    config_name: system.site
