disabled: true
module: node
id: tracker
description: 'Shows all new activity on the system.'
tag: default
base_table: node
human_name: Tracker
core: '8'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: false
      title: 'Recent posts'
      access:
        type: none
      cache:
        type: none
      exposed_form:
        type: basic
      pager:
        type: full
        options:
          items_per_page: '25'
      relationships:
        uid:
          id: uid
          table: node
          field: uid
      fields:
        type:
          id: type
          table: node
          field: type
        title:
          id: title
          table: node
          field: title
        name:
          id: name
          table: users
          field: name
          relationship: uid
          label: Author
        comment_count:
          id: comment_count
          table: node_comment_statistics
          field: comment_count
          label: Replies
        last_comment_timestamp:
          id: last_comment_timestamp
          table: node_comment_statistics
          field: last_comment_timestamp
          label: 'Last Post'
        timestamp:
          id: timestamp
          table: history
          field: timestamp
          label: ''
          link_to_node: 0
          comments: 1
        new_comments:
          id: new_comments
          table: node
          field: new_comments
          label: ''
          hide_empty: true
          suffix: ' new'
          link_to_comment: 1
      sorts:
        last_comment_timestamp:
          id: last_comment_timestamp
          table: node_comment_statistics
          field: last_comment_timestamp
      arguments:
        uid_touch:
          id: uid_touch
          table: node
          field: uid_touch
          exception:
            title_enable: 1
          title_enable: 1
          title: 'Recent posts for %1'
          default_argument_type: fixed
          summary:
            format: default_summary
          specify_validation: 1
      filters:
        status:
          id: status
          table: node
          field: status
          value: '1'
          group: 0
          expose:
            operator: false
      style:
        type: table
        options:
          columns:
            type: type
            title: title
            name: name
            comment_count: comment_count
            last_comment_timestamp: last_comment_timestamp
            timestamp: title
            new_comments: comment_count
          default: last_comment_timestamp
          info:
            type:
              sortable: 1
              separator: ''
            title:
              sortable: 1
              separator: '&nbsp;'
            name:
              sortable: 1
              separator: ''
            comment_count:
              sortable: 1
              separator: '<br />'
            last_comment_timestamp:
              sortable: 1
              separator: '&nbsp;'
            timestamp:
              separator: ''
            new_comments:
              separator: ''
          override: 1
          order: desc
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: tracker
      menu:
        type: normal
        title: 'Recent posts'
