base_field: nid
base_table: node
core: '8'
description: 'A list of other content items which have a link to the content item.'
status: '0'
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: '1'
    display_options:
      query:
        type: views_query
        options:
          query_comment: '0'
      access:
        type: none
      cache:
        type: none
      exposed_form:
        type: basic
      pager:
        type: mini
        options:
          items_per_page: '30'
      empty:
        text:
          id: area
          table: views
          field: area
          empty: '0'
          content: 'No backlinks found.'
          format: '1'
          plugin_id: text
      fields:
        title:
          id: title
          table: node
          field: title
          label: ''
          link_to_node: '1'
          plugin_id: node
      arguments:
        nid:
          id: nid
          table: search_node_links_to
          field: nid
          default_action: 'not found'
          title_enable: '1'
          title: 'Pages that link to %1'
          default_argument_type: fixed
          summary:
            format: default_summary
          specify_validation: '1'
          validate:
            type: node
      filters:
        status:
          id: status
          table: node
          field: status
          value: '1'
          group: '0'
          expose:
            operator: '0'
          plugin_id: boolean
      style:
        type: html_list
        options:
          type: ol
      row:
        type: fields
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: '2'
    display_options:
      query:
        type: views_query
        options: {  }
      path: node/%/backlinks
      menu:
        type: tab
        title: 'What links here'
        weight: '0'
  block_1:
    id: block
    display_title: 'What links here'
    display_plugin: block
    position: '3'
    display_options:
      query:
        type: views_query
        options: {  }
        defaults:
          use_more: '0'
          style_plugin: '0'
          style_options: '0'
          row_plugin: '0'
          row_options: '0'
          arguments: '0'
      use_more: '1'
      arguments:
        nid:
          id: nid
          table: search_node_links_to
          field: nid
          default_action: default
          title_enable: '1'
          title: 'What links here'
          default_argument_type: node
          summary:
            format: default_summary
          specify_validation: '1'
          validate:
            type: node
      style:
        type: html_list
      row:
        type: fields
label: Backlinks
module: search
id: backlinks
tag: default
langcode: en
